### ISSUE TITLE
Initial design

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/rcubed#2]
- [ ] What are the components?
- [ ] Initial schema for virtual database of all the components and codelists, see #6 
- [ ] How should we lay out the property hierarchies and corresponding class hierarchies, see #1 
- [ ] Derive some specifications from existing use in gss-utils #5

**Comment by ajtucker** [comment]
I've knocked up some diagrams for the current architecture in terms of the [components, their dependencies](https://gss-cogs.github.io/gss-data-docs/architecture/components.html) and the [processes and resources used in a transformation pipeline](https://gss-cogs.github.io/gss-data-docs/architecture/transformation.html).

**Comment by LPerryman** [comment]
This is so cool!
I think I've been living in a bubble since i did my commuting degree, their
are so many things I have never heard of until I started this job, jenkins,
docker, ruby, groovy, clojure and more!!!!
